version: '3.7'

services:
  django_gunicorn:
    build:
      context: .
    volumes:
      - media:/media
      - static:/static
    env_file:
      - .env
    ports:
    - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    networks:
      - hututoo-frontend-tier
    volumes:
      - hututoo_build:/hututoo/www

  db:
    image: postgres
    environment:
      - POSTGRES_USER=hututoo
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/posgresql/data

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:8080
      - 443:443
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf/:/etc/letsencrypt
      - hututoo_build:/var/www/hututoo
      - media:/media
      - static:/static
      - pgdata:/pgdata
    depends_on:
      - django_gunicorn

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  static:
  media:
  hututoo_build:
  pgdata:
